spring:
  application:
    name: fotoradar-data-service
  datasource:
    url: jdbc:postgresql://db_fotoradar:5432/fotoradar_db
    username: user_fotoradar
    password: password_fotoradar
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    bootstrap-servers: kafka:9093
    consumer:
      group-id: fotoradar-data-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: '*' #toDO zmień na produkcji

server:
  port: 8080